export const ACCENTS = {
    iris:     { label: 'Ирис',        hue: 290, c: 0.25,  L: 60, swatch: 'oklch(60% 0.25 290)' },
    navy:     { label: 'Темно-синий', hue: 260, c: 0.10,  L: 38, swatch: 'oklch(38% 0.10 260)' },
    midnight: { label: 'Полночь',     hue: 245, c: 0.06,  L: 28, swatch: 'oklch(28% 0.06 245)' },
    forest:   { label: 'Лес',         hue: 150, c: 0.08,  L: 42, swatch: 'oklch(42% 0.08 150)' },
    emerald:  { label: 'Изумруд',     hue: 165, c: 0.10,  L: 46, swatch: 'oklch(46% 0.10 165)' },
    claret:   { label: 'Кларет',      hue: 18,  c: 0.12,  L: 42, swatch: 'oklch(42% 0.12 18)'  },
    burgundy: { label: 'Бордовый',    hue: 10,  c: 0.09,  L: 32, swatch: 'oklch(32% 0.09 10)'  },
    sienna:   { label: 'Сиена',       hue: 40,  c: 0.11,  L: 48, swatch: 'oklch(48% 0.11 40)'  },
    bronze:   { label: 'Бронза',      hue: 55,  c: 0.10,  L: 52, swatch: 'oklch(52% 0.10 55)'  },
    ochre:    { label: 'Охра',        hue: 80,  c: 0.12,  L: 58, swatch: 'oklch(58% 0.12 80)'  },
    slate:    { label: 'Сланец',      hue: 240, c: 0.03,  L: 48, swatch: 'oklch(48% 0.03 240)' },
    graphite: { label: 'Графит',      hue: 270, c: 0.015, L: 34, swatch: 'oklch(34% 0.015 270)' },
    plum:     { label: 'Слива',       hue: 340, c: 0.15,  L: 52, swatch: 'oklch(52% 0.15 340)' },
    teal:     { label: 'Бирюза',      hue: 195, c: 0.13,  L: 64, swatch: 'oklch(64% 0.13 195)' },
    lime:     { label: 'Лайм',        hue: 130, c: 0.20,  L: 72, swatch: 'oklch(72% 0.20 130)' },
    amber:    { label: 'Янтарь',      hue: 70,  c: 0.18,  L: 75, swatch: 'oklch(75% 0.18 70)'  },
    coral:    { label: 'Коралл',      hue: 25,  c: 0.20,  L: 68, swatch: 'oklch(68% 0.20 25)'  },
    ink:      { label: 'Чернила',     hue: 270, c: 0.02,  L: 20, swatch: 'oklch(20% 0.02 270)' },
};

export const FONT_PAIRS = {
    'geist': {
        sans: "'Geist', ui-sans-serif, system-ui, sans-serif",
        mono: "'Geist Mono', ui-monospace, monospace",
        display: "'Geist', ui-sans-serif, sans-serif",
        label: 'Geist + Geist Mono',
    },
};

export const NAV = [
    {
        group: 'Foundations',
        label: 'Основа',
        items: [
            { id: 'colors',    label: 'Цвета' },
            { id: 'typography', label: 'Типографика' },
            { id: 'spacing',   label: 'Отступы и радиусы' },
        ],
    },
    {
        group: 'Forms',
        label: 'Формы',
        items: [
            { id: 'buttons',   label: 'Кнопки' },
            { id: 'inputs',    label: 'Поля ввода' },
            { id: 'checkbox',  label: 'Чекбоксы' },
            { id: 'radio',     label: 'Радиокнопки' },
            { id: 'toggle',    label: 'Переключатели' },
            { id: 'select',    label: 'Выпадающий список' },
            { id: 'tabs',      label: 'Вкладки' },
            { id: 'segmented', label: 'Сегментный выбор' },
            { id: 'advanced-inputs', label: 'Сложные поля' },
            { id: 'text-editor', label: 'Редактор текста' },
        ],
    },
    {
        group: 'Content',
        label: 'Контент',
        items: [
            { id: 'icons',    label: 'Иконки' },
            { id: 'cards',    label: 'Карточки' },
            { id: 'avatars',  label: 'Аватары и метки' },
            { id: 'table',    label: 'Таблица' },
            { id: 'charts',   label: 'Графики' },
            { id: 'graph',    label: 'Графы' },
            { id: 'sliders',  label: 'Слайдеры и прогресс' },
            { id: 'data',     label: 'Данные' },
            { id: 'timeline', label: 'Таймлайн' },
            { id: 'kanban',   label: 'Канбан' },
        ],
    },
    {
        group: 'Navigation',
        label: 'Навигация',
        items: [
            { id: 'navbars',     label: 'Верхняя навигация' },
            { id: 'breadcrumbs', label: 'Хлебные крошки' },
            { id: 'sidebar',     label: 'Боковая навигация' },
            { id: 'scrollbar',   label: 'Скроллбар' },
            { id: 'palette',     label: 'Палитра команд' },
            { id: 'tree',        label: 'Дерево' },
        ],
    },
    {
        group: 'Feedback',
        label: 'Обратная связь',
        items: [
            { id: 'loaders',   label: 'Индикаторы' },
            { id: 'skeletons', label: 'Скелетоны' },
            { id: 'modal',     label: 'Модальное окно' },
            { id: 'tooltip',   label: 'Подсказка' },
            { id: 'toast',     label: 'Уведомление' },
            { id: 'dialogs',   label: 'Диалоги' },
            { id: 'drawer',    label: 'Выезжающая панель' },
            { id: 'coachmark', label: 'Обучающая подсказка' },
        ],
    },
    {
        group: 'Special',
        label: 'Особые',
        items: [
            { id: 'user-menu', label: 'Меню пользователя' },
            { id: 'chat',      label: 'Чат' },
            { id: 'kbd',       label: 'Клавиши' },
            { id: 'map',       label: 'Карта' },
            { id: 'diff',      label: 'Сравнение' },
            { id: 'code',      label: 'Код' },
        ],
    },
    {
        group: 'Page Patterns',
        label: 'Паттерны страниц',
        items: [
            { id: 'auth',     label: 'Авторизация' },
            { id: 'settings', label: 'Настройки' },
            { id: 'wizard',   label: 'Мастер' },
            { id: 'pricing',  label: 'Тарифы' },
            { id: 'error',    label: 'Ошибка' },
        ],
    },
];
